// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0f6Re3wk5iXjEG3tmDD0JHMIhzdSoyY8',
    appId: '1:865060220408:web:44c68b102d97dd8364ba0d',
    messagingSenderId: '865060220408',
    projectId: 'eos-chatting-ecf4b',
    authDomain: 'eos-chatting-ecf4b.firebaseapp.com',
    storageBucket: 'eos-chatting-ecf4b.appspot.com',
    measurementId: 'G-W3YBZMM9YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOeC78-r27N03OZrAgclrFJa23akdoiD4',
    appId: '1:865060220408:android:c0cfbd0b9d0da25964ba0d',
    messagingSenderId: '865060220408',
    projectId: 'eos-chatting-ecf4b',
    storageBucket: 'eos-chatting-ecf4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZoqZjPVF5Qnwlqsc87B--jQaMSWO2iBY',
    appId: '1:865060220408:ios:2db15fa93135964264ba0d',
    messagingSenderId: '865060220408',
    projectId: 'eos-chatting-ecf4b',
    storageBucket: 'eos-chatting-ecf4b.appspot.com',
    iosClientId: '865060220408-1i49b7proj2pqv8dm67bq65pqtcuqk3e.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
